# Dies ist eine Chef generierte Datei. Manuelle Änderungen gehen u.U. verloren!

# Set up the prompt
autoload -Uz promptinit
promptinit

# Prompt (PS1) für root und non-root unterschiedlich
if [[ $(id -u) = "0" ]]; then
	# Root
	prompt adam2 red faint yellow white
else
	# Nicht Root
	prompt fire cyan faint cyan green yellow white
fi

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=10000
SAVEHIST=100000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# Lade die Shell unabhaengige Shell Aliases Datei
[[ -r ~/.sh_aliases ]] && . ~/.sh_aliases

# Lade EveryWare bash_franzi Shell Auditing
[[ -f /etc/bash_audit/bash_audit ]] && . /etc/bash_audit/bash_audit

# EOF
